Added enable_pec to Enable/Disable PEC
kplindegaard/smbus2 pull request #53
Opened 2020-09-08 13:57 UTC by rgusmero

Added member function enable_pec to SMBus to Enable/Disable PEC (Packet Error Checking, see SMBus 1.1 and later).

Some devices require it (e.g. MLX90614), in particular when writing data (because they expect - and check - 1 more byte, i.e. the PEC crc, in the data string).

Example:
    bus=smbus2.SMBus(1)
    bus.enable_pec()

2020-09-09 06:13 UTC, kplindegaard requested changes
Thanks! I have a couple of small changes I would like you to take a look at.

2020-09-09 06:13 UTC, kplindegaard commented on smbus2/smbus2.py
> +    def enable_pec(self, enable=True):
Thanks, @rgusmero. I have a couple of comments I hope you don't mind to take care of. The first one is that I would like the interface of `smbus2` to match that of smbus-cffi to keep the drop-in replacement alternative intact. Thus, I would like you to change the method name and header to
```Python
pec(self, enable):
```
and let any non-zero value be interpreted as `True`.

2020-09-09 06:13 UTC, kplindegaard commented on smbus2/smbus2.py
> +
Here you need to document the input parameter(s). Please see documentation elsewhere in the code for reference.

2020-09-09 06:13 UTC, kplindegaard commented on smbus2/smbus2.py
> +            raise ValueError('SMBUS_PEC is not a feature')
Perhaps better to raise an `IOError` in this case?

2020-09-09 06:13 UTC, kplindegaard commented on smbus2/smbus2.py
> +        ioctl(self.fd,I2C_PEC,int(enable))
Nitpick: Please use space between the parameter.

2020-09-09 06:52 UTC, rgusmero commented
Done as requested with a small change: insetead of changing the member funcion name, I introduced a setter-only property. This allows to use the old syntax bus.pec=1 and thus better accomplishes the drop-in compatibility requirement.

2020-12-05 07:37 UTC, kplindegaard approved these changes

2020-12-05 07:40 UTC, merged